export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOADING_PAYMENTS = 'LOADING_PAYMENTS';
export const FINISHED_LOADING_PAYMENTS = 'FINISHED_LOADING_PAYMENTS';
export const LOADING_PAYMENTS_FAILED = 'LOADING_PAYMENTS_FAILED';