export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOADING_PAYMENTS = 'LOADING_PAYMENTS';
export const FINISHED_LOADING_PAYMENTS = 'FINISHED_LOADING_PAYMENTS';
export const LOADING_PAYMENTS_FAILED = 'LOADING_PAYMENTS_FAILED';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const FINISHED_LOADING_PRODUCTS = 'FINISHED_LOADING_PRODUCTS';
export const LOADING_PRODUCTS_FAILED = 'LOADING_PRODUCTS_FAILED';

export const LOADING_CUSTOMERS = 'LOADING_CUSTOMERS';
export const FINISHED_LOADING_CUSTOMERS = 'FINISHED_LOADING_CUSTOMERS';
export const LOADING_CUSTOMERS_FAILED = 'LOADING_CUSTOMERS_FAILED';