export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOADING_PAYMENTS = 'LOADING_PAYMENTS';
export const FINISHED_LOADING_PAYMENTS = 'FINISHED_LOADING_PAYMENTS';
export const LOADING_PAYMENTS_FAILED = 'LOADING_PAYMENTS_FAILED';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const FINISHED_LOADING_PRODUCTS = 'FINISHED_LOADING_PRODUCTS';
export const LOADING_PRODUCTS_FAILED = 'LOADING_PRODUCTS_FAILED';

export const LOADING_CUSTOMERS = 'LOADING_CUSTOMERS';
export const FINISHED_LOADING_CUSTOMERS = 'FINISHED_LOADING_CUSTOMERS';
export const LOADING_CUSTOMERS_FAILED = 'LOADING_CUSTOMERS_FAILED';

export const LOADING_ORDERS = 'LOADING_ORDERS';
export const FINISHED_LOADING_ORDERS = 'FINISHED_LOADING_ORDERS';
export const LOADING_ORDERS_FAILED = 'LOADING_ORDERS_FAILED';

export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const UPDATING_PROFILE = "UPDATING_PROFILE";
export const UPDATED_PROFILE = "UPDATED_PROFILE";
export const FAILED_TO_UPDATE_PROFILE = "FAILED_TO_UPDATE_PROFILE";

export const UPDATING_BANK_ACCOUNT = "UPDATING_BANK_ACCOUNT";
export const UPDATED_BANK_ACCOUNT = "UPDATED_BANK_ACCOUNT";
export const FAILED_TO_UPDATE_BANK_ACCOUNT = "FAILED_TO_UPDATE_BANK_ACCOUNT";

export const UPDATING_USER_TYPE = "UPDATING_USER_TYPE";
export const UPDATED_USER_TYPE = "UPDATED_USER_TYPE";
export const FAILED_TO_UPDATE_USER_TYPE = "FAILED_TO_UPDATE_USER_TYPE";

export const UPDATING_API_SETTING = "UPDATING_API_SETTING";
export const UPDATED_API_SETTING  = "UPDATED_API_SETTING";
export const FAILED_TO_UPDATE_API_SETTING  = "FAILED_TO_UPDATE_API_SETTING";

export const UPDATING_NOTIFICATION_SETTING = "UPDATING_NOTIFICATION_SETTING";
export const UPDATED_NOTIFICATION_SETTING  = "UPDATED_NOTIFICATION_SETTING";
export const FAILED_TO_UPDATE_NOTIFICATION_SETTING  = "FAILED_TO_UPDATE_NOTIFICATION_SETTING";